Version bump to 2.13.9

diff --git a/openrc_icinga2 b/openrc_icinga2
--- a/openrc_icinga2
+++ b/openrc_icinga2
@@ -1,188 +1,138 @@
-#!/bin/sh
-#
-# chkconfig: 35 90 12
-# description: Icinga 2
-#
-### BEGIN INIT INFO
-# Provides:          icinga2
-# Required-Start:    $remote_fs $syslog $network
-# Required-Stop:     $remote_fs $syslog $network
-# Should-Start:      mysql postgresql
-# Should-Stop:       mysql postgresql
-# Default-Start:     2 3 5
-# Default-Stop:      0 1 6
-# Short-Description: icinga2 host/service/network monitoring and management system
-# Description:       Icinga 2 is a monitoring and management system for hosts, services and networks.
-### END INIT INFO
+#!/usr/bin/openrc-run
 
-# Get function from functions library
-if [ -f /etc/rc.d/init.d/functions ]; then
-	. /etc/rc.d/init.d/functions
-elif [ -f /etc/init.d/functions ]; then
-	. /etc/init.d/functions
-fi
+description="Icinga 2 is a monitoring and management system for hosts, services and networks."
 
-# load system specific defines
-SYSCONFIGFILE=/etc/conf.d/icinga2
-if [ -f $SYSCONFIGFILE ]; then
-	. $SYSCONFIGFILE
-else
-	echo "Couldn't load system specific defines from $SYSCONFIGFILE. Using defaults."
-fi
+extra_commands="checkconfig"
+extra_started_commands="reload"
 
-# Set defaults, to overwrite see "/etc/conf.d/icinga2"
+depend() {
+  need net
+  after network
+}
 
-: ${ICINGA2_USER:="icinga"}
-: ${ICINGA2_GROUP:="icinga"}
-: ${ICINGA2_COMMAND_GROUP:="icingacmd"}
-: ${DAEMON:="/usr/bin/icinga2"}
-: ${ICINGA2_CONFIG_FILE:="/etc/icinga2/icinga2.conf"}
-: ${ICINGA2_ERROR_LOG:=/var/log/icinga2/error.log}
-: ${ICINGA2_STARTUP_LOG:=/var/log/icinga2/startup.log}
-: ${ICINGA2_PID_FILE:="/run/icinga2/icinga2.pid"}
+start_pre() {
 
-# Load extra environment variables
-if [ -f /etc/default/icinga2 ]; then
-	. /etc/default/icinga2
-fi
+  if [ ! -e $ICINGA2_CONFIG_FILE ]; then
+    eerror "Config file '$ICINGA2_CONFIG_FILE' does not exist."
+    exit 6
+  fi
 
-test -x $DAEMON || exit 5
+  getent passwd $ICINGA2_USER >/dev/null 2>&1 || (echo "Icinga user '$ICINGA2_USER' does not exist. Exiting." && exit 6)
+  getent group $ICINGA2_GROUP >/dev/null 2>&1 || (echo "Icinga group '$ICINGA2_GROUP' does not exist. Exiting." && exit 6)
+  getent group $ICINGA2_COMMAND_GROUP >/dev/null 2>&1 || (echo "Icinga command group '$ICINGA2_COMMAND_GROUP' does not exist. Exiting." && exit 6)
 
-if [ ! -e $ICINGA2_CONFIG_FILE ]; then
-	echo "Config file '$ICINGA2_CONFIG_FILE' does not exist."
-	exit 6
-fi
-
-getent passwd $ICINGA2_USER >/dev/null 2>&1 || (echo "Icinga user '$ICINGA2_USER' does not exist. Exiting." && exit 6)
-getent group $ICINGA2_GROUP >/dev/null 2>&1 || (echo "Icinga group '$ICINGA2_GROUP' does not exist. Exiting." && exit 6)
-getent group $ICINGA2_COMMAND_GROUP >/dev/null 2>&1 || (echo "Icinga command group '$ICINGA2_COMMAND_GROUP' does not exist. Exiting." && exit 6)
+  if [ "${RC_CMD}" = "restart" ] ; then
+      checkconfig || return $?
+  fi
+}
 
 # Start Icinga 2
 start() {
-	printf "Starting Icinga 2: "
-	/usr/lib/icinga2/prepare-dirs "$SYSCONFIGFILE"
+  ebegin "Starting Icinga 2: "
 
-	if ! $DAEMON daemon -c $ICINGA2_CONFIG_FILE -d -e $ICINGA2_ERROR_LOG > $ICINGA2_STARTUP_LOG 2>&1; then
-		echo "Error starting Icinga. Check '$ICINGA2_STARTUP_LOG' for details."
-		exit 1
-	else
-		echo "Done"
-	fi
+  /usr/lib/icinga2/prepare-dirs "$SYSCONFIGFILE"
+
+  if ! $DAEMON daemon --config $ICINGA2_CONFIG_FILE --daemonize --errorlog $ICINGA2_ERROR_LOG > $ICINGA2_STARTUP_LOG 2>&1
+  then
+    eerror "Error starting Icinga. Check '$ICINGA2_STARTUP_LOG' for details."
+    eend 1
+  else
+    einfo "Done"
+  fi
 }
 
 # Restart Icinga 2
 stop() {
-	printf "Stopping Icinga 2: "
+  ebegin  "Stopping Icinga 2: "
 
-	if [ ! -e $ICINGA2_PID_FILE ]; then
-		echo "The PID file '$ICINGA2_PID_FILE' does not exist."
-		if [ "x$1" = "xnofail" ]; then
-			return
-		else
-			exit 7
-		fi
-	fi
+  if [ ! -e $ICINGA2_PID_FILE ]
+  then
+    eerror "The PID file '$ICINGA2_PID_FILE' does not exist."
+    if [ "x$1" = "xnofail" ]
+    then
+      return
+    else
+      eend 7
+    fi
+  fi
 
-	pid=`cat $ICINGA2_PID_FILE`
+  pid=$(cat $ICINGA2_PID_FILE)
 
-	if icinga2 internal signal -s SIGINT -p $pid >/dev/null 2>&1; then
-		for i in 1 2 3 4 5 6 7 8 9 10; do
-		if ! icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1; then
-				break
-			fi
+  if icinga2 internal signal -s SIGINT -p $pid >/dev/null 2>&1
+  then
+  for i in $(seq 1 10); do
+    if ! icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1
+    then
+      break
+    fi
+    sleep 3
+  done
+  fi
 
-			printf '.'
-			sleep 3
-		done
-	fi
+  if icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1
+  then
+    icinga2 internal signal -s SIGKILL -p $pid >/dev/null 2>&1
+  fi
 
-	if icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1; then
-		icinga2 internal signal -s SIGKILL -p $pid >/dev/null 2>&1
-	fi
-
-	echo "Done"
+  eend $?
 }
 
 # Reload Icinga 2
 reload() {
-	exec /usr/lib/icinga2/safe-reload "$SYSCONFIGFILE"
+
+  checkconfig || return $?
+  ebegin "Reloading ${RC_SVCNAME}"
+  exec /usr/lib/icinga2/safe-reload "$SYSCONFIGFILE"
+  eend $?
 }
 
 # Check the Icinga 2 configuration
 checkconfig() {
-	printf "Checking configuration: "
+  ebegin "Checking configuration: "
 
-	if ! $DAEMON daemon -c $ICINGA2_CONFIG_FILE -C > $ICINGA2_STARTUP_LOG 2>&1; then
-		if [ "x$1" = "x" ]; then
-			cat $ICINGA2_STARTUP_LOG
-			echo "Icinga 2 detected configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
-			exit 1
-		else
-			echo "Not "$1"ing Icinga 2 due to configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
-			if [ "x$2" = "xfail" ]; then
-				exit 1
-			fi
-		fi
-	fi
+  if ! $DAEMON daemon --config $ICINGA2_CONFIG_FILE --validate > $ICINGA2_STARTUP_LOG 2>&1
+  then
+    if [ "x$1" = "x" ]
+    then
+      cat $ICINGA2_STARTUP_LOG
+      einfo "Icinga 2 detected configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
+      eend 1
+    else
+      einfo "Not "$1"ing Icinga 2 due to configuration errors. Check '$ICINGA2_STARTUP_LOG' for details."
+      if [ "x$2" = "xfail" ]
+      then
+        eend 1
+      fi
+    fi
+  fi
 
-	echo "Done"
-	# no arguments requires full output
-	if [ "x$1" = "x" ]; then
-		cat $ICINGA2_STARTUP_LOG
-	fi
+  einfo "Done"
+  # no arguments requires full output
+  if [ "x$1" = "x" ]
+  then
+    cat $ICINGA2_STARTUP_LOG
+  fi
 }
 
 # Print status for Icinga 2
 status() {
-	printf "Icinga 2 status: "
 
-	if [ ! -e $ICINGA2_PID_FILE ]; then
-		echo "Not running"
-		exit 3
-	fi
+  ebegin "Icinga 2 status: "
 
-	pid=`cat $ICINGA2_PID_FILE`
-	if icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1; then
-		echo "Running"
-	else
-		echo "Not running"
-		exit 3
-	fi
+  if [ ! -e $ICINGA2_PID_FILE ]
+  then
+    eerror "Not running"
+    eend 3
+  fi
+
+  pid=`cat $ICINGA2_PID_FILE`
+  if icinga2 internal signal -s SIGCHLD -p $pid >/dev/null 2>&1
+  then
+    einfo "Running"
+  else
+    eerror "Not running"
+    eend 3
+  fi
 }
 
-### main logic ###
-case "$1" in
-  start)
-	checkconfig start fail
-	start
-  ;;
-  stop)
-	stop
-	;;
-  status)
-	status
-  ;;
-  restart)
-	checkconfig restart fail
-	stop nofail
-	start
-  ;;
-  condrestart)
-	STATUS=$(status > /dev/null 2>&1)
-	if [ $? != 0 ]; then exit 0; fi
-	checkconfig restart fail
-	stop nofail
-	start
-  ;;
-  reload)
-	reload
-  ;;
-  checkconfig)
-	checkconfig
-  ;;
-  *)
-	echo "Usage: $0 {start|stop|restart|reload|checkconfig|status}"
-	exit 3
-esac
-
-exit 0
+# exit 0
